### ISSUE TITLE
[PasscodeLock]Add Language Select

### ISSUE THREAD

**Issue by Danik2343** [arg0NNY/DiscordPlugins#23]
[PasscodeLock]Add Language Select
I want to translate this plugin to Russian, Ukrainian and Belarusian.

**Comment by arg0NNY** [comment]
So you're suggesting me to translate the plugin into different languages?

**Comment by Danik2343** [comment]
I suggest that the choice of localization be made in the settings. I will translate the plugin into these 3 languages.

**Comment by Snaklilopin** [comment]
Create a translations page on crowdin so that people can localize for their languages, I think for such a plugin it will not be superfluous.
Well, I think Danik wanted to convey this idea so that this plugin would be translated, So it seems to be clear who and what to poke, but for convenience it would not be superfluous to read in your own language

**Comment by arg0NNY** [comment]
Translate here: https://crwd.in/betterdiscord-passcodelock
