### ISSUE TITLE
Passcode Lock not working

### ISSUE THREAD

**Issue by Bennett-Fourr** [arg0NNY/DiscordPlugins#76]
Pass code Lock gives error 
"Plugin constructor() could not be fired."

**Comment by lupus0802** [comment]
This issue has been fixed in version 1.4.4. If you do not automatically get an update request, please re-download the plugin. 
Note that when setting a keybind the keybind may not show correctly, however, it is set in the configuration.
See also https://github.com/BetterDiscord/BetterDiscord/issues/1686

**Comment by iYouseFF** [comment]
i have the same issue, i'm on version 1.4.4 and the patch notes says it is fixed for the latest discord update, i tried deleting the plugin and re downloading it but nothing changed
![image](https://github.com/arg0NNY/DiscordPlugins/assets/47045475/4d813be1-1935-4c47-88c1-8d0458fa2e01)
![image](https://github.com/arg0NNY/DiscordPlugins/assets/47045475/c470a2cc-26ac-4c25-a213-0c4a70bae560)

**Comment by Bennett-Fourr** [comment]
I had to reinstall better discord and discord and delete a file associated with it.

**Comment by lupus0802** [comment]
@iYouseFF Your issue is related to the configuration file. The easiest fix is to just delete the file PasscodeLock.config.json and restart discord. It'll erase your settings but allows the plugin to start again.
